version: "2"
services: 
    nodeapp:
        build: 
            context: .
            dockerfile: .docker/Dockerfile
        ports: 
            - "3000:3000"
        volumes: 
            - .:/usr/app
        tty: true